-- MySQL Script generated by MySQL Workbench
-- Fri Sep  9 09:16:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `servico` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `data solicitacao` VARCHAR(45) NULL,
  `liberado` TINYINT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `nivel helpdesk` INT NULL,
  `nome` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Ordem de Serviço_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Análisa de Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Análisa de Pedido` (
  `Responsavel_idResponsavel` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Responsavel_idResponsavel`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Responsavel_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Responsavel_has_Pedido_Responsavel1_idx` (`Responsavel_idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_has_Pedido_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `mydb`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsavel_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(25) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`StatusOrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`StatusOrdemServico` (
  `idStatusOrdemServico` INT NOT NULL,
  `identificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatusOrdemServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdemServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdemServico` (
  `idOrdemServico` INT NOT NULL,
  `codigo` INT NOT NULL,
  `dataemissao` DATE NOT NULL,
  `dataconclusao` DATE NULL,
  `valor` DECIMAL(18,2) NULL,
  `autorizacao` VARCHAR(45) NULL,
  `obs` TEXT(100) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `StatusOrdemServico_idStatusOrdemServico` INT NOT NULL,
  PRIMARY KEY (`idOrdemServico`, `Cliente_idCliente`, `StatusOrdemServico_idStatusOrdemServico`),
  INDEX `fk_OrdemServico_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_OrdemServico_StatusOrdemServico1_idx` (`StatusOrdemServico_idStatusOrdemServico` ASC) VISIBLE,
  CONSTRAINT `fk_OrdemServico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrdemServico_StatusOrdemServico1`
    FOREIGN KEY (`StatusOrdemServico_idStatusOrdemServico`)
    REFERENCES `mydb`.`StatusOrdemServico` (`idStatusOrdemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `OrdemServico_idOrdemServico` INT NOT NULL,
  `OrdemServico_Cliente_idCliente` INT NOT NULL,
  `OrdemServico_StatusOrdemServico_idStatusOrdemServico` INT NOT NULL,
  `cor` VARCHAR(20) NOT NULL,
  `placa` VARCHAR(20) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `ano` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idVeiculo`, `OrdemServico_idOrdemServico`, `OrdemServico_Cliente_idCliente`, `OrdemServico_StatusOrdemServico_idStatusOrdemServico`),
  INDEX `fk_Veiculo_OrdemServico1_idx` (`OrdemServico_idOrdemServico` ASC, `OrdemServico_Cliente_idCliente` ASC, `OrdemServico_StatusOrdemServico_idStatusOrdemServico` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_OrdemServico1`
    FOREIGN KEY (`OrdemServico_idOrdemServico` , `OrdemServico_Cliente_idCliente` , `OrdemServico_StatusOrdemServico_idStatusOrdemServico`)
    REFERENCES `mydb`.`OrdemServico` (`idOrdemServico` , `Cliente_idCliente` , `StatusOrdemServico_idStatusOrdemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TabelaServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TabelaServico` (
  `idTabelaServico` INT NOT NULL,
  `peca` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `maodeobra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTabelaServico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `membros` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_OrdemServico_idOrdemServico` INT NOT NULL,
  `Veiculo_OrdemServico_Cliente_idCliente` INT NOT NULL,
  `Veiculo_OrdemServico_StatusOrdemServico_idStatusOrdemServico` INT NOT NULL,
  `Descricao` TEXT(100) NOT NULL,
  `valorpeca` FLOAT NOT NULL,
  `valormaodeobra` FLOAT NOT NULL,
  `datainicio` DATE NULL,
  `dataconlusao` DATE NULL,
  `TabelaServico_idTabelaServico` INT NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`Veiculo_idVeiculo`, `Veiculo_OrdemServico_idOrdemServico`, `Veiculo_OrdemServico_Cliente_idCliente`, `Veiculo_OrdemServico_StatusOrdemServico_idStatusOrdemServico`, `TabelaServico_idTabelaServico`, `Equipe_idEquipe`),
  INDEX `fk_Servico_TabelaServico1_idx` (`TabelaServico_idTabelaServico` ASC) VISIBLE,
  INDEX `fk_Servico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Servico_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_OrdemServico_idOrdemServico` , `Veiculo_OrdemServico_Cliente_idCliente` , `Veiculo_OrdemServico_StatusOrdemServico_idStatusOrdemServico`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo` , `OrdemServico_idOrdemServico` , `OrdemServico_Cliente_idCliente` , `OrdemServico_StatusOrdemServico_idStatusOrdemServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_TabelaServico1`
    FOREIGN KEY (`TabelaServico_idTabelaServico`)
    REFERENCES `mydb`.`TabelaServico` (`idTabelaServico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idMecanico`, `Equipe_idEquipe`),
  INDEX `fk_Mecanico_Equipe1_idx` (`Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(15) NULL,
  `complemento` TEXT(100) NULL,
  `Enderecocol` VARCHAR(45) NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  `Mecanico_Equipe_idEquipe` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `Mecanico_idMecanico`, `Mecanico_Equipe_idEquipe`),
  INDEX `fk_Endereco_Mecanico1_idx` (`Mecanico_idMecanico` ASC, `Mecanico_Equipe_idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico` , `Mecanico_Equipe_idEquipe`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico` , `Equipe_idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
