-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 13:28:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `servico` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `data solicitacao` VARCHAR(45) NULL,
  `liberado` TINYINT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `nivel helpdesk` INT NULL,
  `nome` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Ordem de Serviço_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Análisa de Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Análisa de Pedido` (
  `Responsavel_idResponsavel` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Responsavel_idResponsavel`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Responsavel_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Responsavel_has_Pedido_Responsavel1_idx` (`Responsavel_idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_has_Pedido_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `mydb`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsavel_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tabela_Referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tabela_Referencia` (
  `idTabela de Refêrencia` INT NOT NULL,
  `valor_tabela` FLOAT NULL,
  `identificacao` FLOAT NOT NULL,
  PRIMARY KEY (`idTabela de Refêrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe` (
  `idEquipe` INT NOT NULL,
  `identifica_servicos` VARCHAR(45) NULL,
  `Mecanico/Equipe_Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`idEquipe`, `Mecanico/Equipe_Mecanico_idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  `cor` VARCHAR(45) NULL,
  `placa` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Equipe_Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`, `Equipe_Mecanicos_idEquipe de Mecanicos`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Veiculo_Equipe_Mecanicos1_idx` (`Equipe_Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_Equipe_Mecanicos1`
    FOREIGN KEY (`Equipe_Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem_Servico` (
  `idOrdem_Servico` INT NOT NULL,
  `data de emissao` DATE NULL,
  `valor` INT NULL,
  `status` VARCHAR(45) NULL,
  `data_conclu` DATE NULL,
  `Tabela de Refêrencia_idTabela de Refêrencia` INT NOT NULL,
  `autoriza` VARCHAR(45) NULL,
  `Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem_Servico`, `Tabela de Refêrencia_idTabela de Refêrencia`, `Equipe de Mecanicos_idEquipe de Mecanicos`, `Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`),
  INDEX `fk_OS_Tabela de Refêrencia1_idx` (`Tabela de Refêrencia_idTabela de Refêrencia` ASC) VISIBLE,
  INDEX `fk_OS_Equipe de Mecanicos1_idx` (`Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_Veiculo1_idx` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Tabela de Refêrencia1`
    FOREIGN KEY (`Tabela de Refêrencia_idTabela de Refêrencia`)
    REFERENCES `mydb`.`Tabela_Referencia` (`idTabela de Refêrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico/Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico/Equipe` (
  `Mecanico_idMecanico` INT NOT NULL,
  `Equipe_idEquipe_Mecanicos` INT NOT NULL,
  PRIMARY KEY (`Mecanico_idMecanico`, `Equipe_idEquipe_Mecanicos`),
  INDEX `fk_Equipe de Mecanicos_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Mecanico/Equipe_Equipe1_idx` (`Equipe_idEquipe_Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe de Mecanicos_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico/Equipe_Equipe1`
    FOREIGN KEY (`Equipe_idEquipe_Mecanicos`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `idPeca` INT NOT NULL,
  `identificador` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `valor` DECIMAL(18,2) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`idPeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servico` (
  `idServiço` INT NOT NULL,
  `Equipe_Mecanicos_idEquipe_Mecanicos` INT NOT NULL,
  `Ordem_Servico_idOrdem_Servico` INT NOT NULL,
  `Ordem_Servico_Tabela de Refêrencia_idTabela de Refêrencia` INT NOT NULL,
  `Ordem_Servico_Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  `Ordem_Servico_Veiculo_idVeiculo` INT NOT NULL,
  `Ordem_Servico_Veiculo_Cliente_idCliente` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valor_pecas` VARCHAR(45) NULL,
  `valor_mao_obra` VARCHAR(45) NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  `Peca_idPeca` INT NOT NULL,
  PRIMARY KEY (`idServiço`, `Equipe_Mecanicos_idEquipe_Mecanicos`, `Ordem_Servico_idOrdem_Servico`, `Ordem_Servico_Tabela de Refêrencia_idTabela de Refêrencia`, `Ordem_Servico_Equipe de Mecanicos_idEquipe de Mecanicos`, `Ordem_Servico_Veiculo_idVeiculo`, `Ordem_Servico_Veiculo_Cliente_idCliente`, `Peca_idPeca`),
  INDEX `fk_Serviço_Equipe de Mecanicos1_idx` (`Equipe_Mecanicos_idEquipe_Mecanicos` ASC) VISIBLE,
  INDEX `fk_Servico_Ordem_Servico1_idx` (`Ordem_Servico_idOrdem_Servico` ASC, `Ordem_Servico_Tabela de Refêrencia_idTabela de Refêrencia` ASC, `Ordem_Servico_Equipe de Mecanicos_idEquipe de Mecanicos` ASC, `Ordem_Servico_Veiculo_idVeiculo` ASC, `Ordem_Servico_Veiculo_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Servico_Peca1_idx` (`Peca_idPeca` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe_Mecanicos_idEquipe_Mecanicos`)
    REFERENCES `mydb`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Ordem_Servico1`
    FOREIGN KEY (`Ordem_Servico_idOrdem_Servico` , `Ordem_Servico_Tabela de Refêrencia_idTabela de Refêrencia` , `Ordem_Servico_Equipe de Mecanicos_idEquipe de Mecanicos` , `Ordem_Servico_Veiculo_idVeiculo` , `Ordem_Servico_Veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`Ordem_Servico` (`idOrdem_Servico` , `Tabela de Refêrencia_idTabela de Refêrencia` , `Equipe de Mecanicos_idEquipe de Mecanicos` , `Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico_Peca1`
    FOREIGN KEY (`Peca_idPeca`)
    REFERENCES `mydb`.`Peca` (`idPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
