-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 11:46:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `servico` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `data solicitacao` VARCHAR(45) NULL,
  `liberado` TINYINT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `nivel helpdesk` INT NULL,
  `nome` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idResponsavel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Ordem de Serviço_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Análisa de Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Análisa de Pedido` (
  `Responsavel_idResponsavel` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Responsavel_idResponsavel`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Responsavel_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Responsavel_has_Pedido_Responsavel1_idx` (`Responsavel_idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_has_Pedido_Responsavel1`
    FOREIGN KEY (`Responsavel_idResponsavel`)
    REFERENCES `mydb`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Responsavel_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico` (
  `idMecanico` INT NOT NULL,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `especialidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idMecanico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tabela de Refêrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tabela de Refêrencia` (
  `idTabela de Refêrencia` INT NOT NULL,
  `valor servico` FLOAT NULL,
  `valor peca` FLOAT NULL,
  PRIMARY KEY (`idTabela de Refêrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipe de Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipe de Mecanicos` (
  `idEquipe de Mecanicos` INT NOT NULL,
  `identifica os servicos` VARCHAR(45) NULL,
  PRIMARY KEY (`idEquipe de Mecanicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serviço` (
  `idServiço` INT NOT NULL,
  `avaliacao` VARCHAR(45) NULL,
  `executar` VARCHAR(45) NULL,
  `Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  PRIMARY KEY (`idServiço`, `Equipe de Mecanicos_idEquipe de Mecanicos`),
  INDEX `fk_Serviço_Equipe de Mecanicos1_idx` (`Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Serviço_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe de Mecanicos` (`idEquipe de Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OS` (
  `idOS` INT NOT NULL,
  `data de emissao` DATE NULL,
  `valor` INT NULL,
  `status` VARCHAR(45) NULL,
  `data de conclusao` DATE NULL,
  `Tabela de Refêrencia_idTabela de Refêrencia` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `autoriza` VARCHAR(45) NULL,
  `Serviço_idServiço` INT NOT NULL,
  `Serviço_Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  `Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  PRIMARY KEY (`idOS`, `Tabela de Refêrencia_idTabela de Refêrencia`, `Cliente_idCliente`, `Serviço_idServiço`, `Serviço_Equipe de Mecanicos_idEquipe de Mecanicos`, `Equipe de Mecanicos_idEquipe de Mecanicos`),
  INDEX `fk_OS_Tabela de Refêrencia1_idx` (`Tabela de Refêrencia_idTabela de Refêrencia` ASC) VISIBLE,
  INDEX `fk_OS_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_OS_Serviço1_idx` (`Serviço_idServiço` ASC, `Serviço_Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  INDEX `fk_OS_Equipe de Mecanicos1_idx` (`Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Tabela de Refêrencia1`
    FOREIGN KEY (`Tabela de Refêrencia_idTabela de Refêrencia`)
    REFERENCES `mydb`.`Tabela de Refêrencia` (`idTabela de Refêrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Serviço1`
    FOREIGN KEY (`Serviço_idServiço` , `Serviço_Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Serviço` (`idServiço` , `Equipe de Mecanicos_idEquipe de Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe de Mecanicos` (`idEquipe de Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `idVeiculo` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`, `Cliente_idCliente`),
  INDEX `fk_Veiculo_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo possui Equipe de Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo possui Equipe de Mecanicos` (
  `Veiculo_idVeiculo` INT NOT NULL,
  `Veiculo_Cliente_idCliente` INT NOT NULL,
  `Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  PRIMARY KEY (`Veiculo_idVeiculo`, `Veiculo_Cliente_idCliente`, `Equipe de Mecanicos_idEquipe de Mecanicos`),
  INDEX `fk_Veiculo_has_Equipe de Mecanicos_Equipe de Mecanicos1_idx` (`Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  INDEX `fk_Veiculo_has_Equipe de Mecanicos_Veiculo1_idx` (`Veiculo_idVeiculo` ASC, `Veiculo_Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Veiculo_has_Equipe de Mecanicos_Veiculo1`
    FOREIGN KEY (`Veiculo_idVeiculo` , `Veiculo_Cliente_idCliente`)
    REFERENCES `mydb`.`Veiculo` (`idVeiculo` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Veiculo_has_Equipe de Mecanicos_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe de Mecanicos` (`idEquipe de Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecanico possui Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecanico possui Equipe` (
  `Equipe de Mecanicos_idEquipe de Mecanicos` INT NOT NULL,
  `Mecanico_idMecanico` INT NOT NULL,
  PRIMARY KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`, `Mecanico_idMecanico`),
  INDEX `fk_Equipe de Mecanicos_has_Mecanico_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  INDEX `fk_Equipe de Mecanicos_has_Mecanico_Equipe de Mecanicos1_idx` (`Equipe de Mecanicos_idEquipe de Mecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe de Mecanicos_has_Mecanico_Equipe de Mecanicos1`
    FOREIGN KEY (`Equipe de Mecanicos_idEquipe de Mecanicos`)
    REFERENCES `mydb`.`Equipe de Mecanicos` (`idEquipe de Mecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipe de Mecanicos_has_Mecanico_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `mydb`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
